kind: Service
apiVersion: v1
metadata:
  name: spring-boot-tomcat-svc
  namespace: spring-boot
spec:
  selector:
    app: spring
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
