apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-boot-tomcat-lb
  namespace: spring-boot
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: spring-boot.192.168.137.172.xip.io
    http:
      paths:
      - backend:
          serviceName: spring-boot-tomcat-svc
          servicePort: 8080
        path: /
